### ISSUE TITLE
Use of write to characteristic in line 178

### ISSUE THREAD

**Issue by fzuerkeraguilar** [teco-kit/cosinuss-flutter#1]
What do the values written to the characteristic affect? Where do they come from?
https://github.com/teco-kit/cosinuss-flutter/blob/4a028af8e8c7dd32bbcb14ea07616c99b6373cea/lib/main.dart#L178

**Comment by TobiasRoeddiger** [comment]
Great question! They have been extracted from the Cosinuss App which was decompiled to reverse engineer the GATT API. It’s like a „key“ that enables the sampling of the sensors of the Cosinuss earbud.
